set(CMAKE_SYSTEM_NAME WindowsStore)
set(CMAKE_SYSTEM_VERSION 10.0)
set(CMAKE_SYSTEM_PROCESSOR x64)
set(CMAKE_WIN32_EXECUTABLE ON)

set(CMAKE_C_COMPILER cl.exe)

set(CMAKE_C_FLAGS "/O2 /W3")
set(CMAKE_C_FLAGS_DEBUG "/Zi /W3")

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
