set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

set(CMAKE_C_COMPILER cl.exe)

set(CMAKE_C_FLAGS_RELEASE "/O2 /W3")
set(CMAKE_C_FLAGS_DEBUG "/Zi //DEBUG:FULL /W3")

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
